gui:
  image: ubuntu:14.04
  volumes:
  - /tmp/.X11-unix:/tmp/.X11-unix
  - ${HOME}:/home/developer
webstorm:
  image: uptownhr/docker-webstorm
  volumes_from:
  - gui
  environment:
  - DISPLAY=${DISPLAY}
